default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: blog_db_development

test:
  <<: *default
  database: blog_db_test

production:
  <<: *default
  database: blog_db_production
